fos_user:
  db_driver: mongodb # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: AppBundle\Entity\User
  from_email:
    address: "e-boudhina@live.fr"
    sender_name: "e-boudhina"



